In [1]:
import pandas as pd 
import os

In [2]:
data_path = os.path.join('..','data', 'raw', 'dados_completos.csv')
df = pd.read_csv(data_path)
df

           data    4393  21084  24369  27640  4390      24364
0    2012-03-01  164.42   5.36    8.0   1.95  0.82   98.06309
1    2012-04-01  164.99   5.41    7.8   1.88  0.71   98.38205
2    2012-05-01  163.05   5.51    7.7   1.78  0.74   99.62478
3    2012-06-01  162.35   5.43    7.6   1.70  0.64  100.33945
4    2012-07-01  160.56   5.42    7.5   1.72  0.68  100.51105
..          ...     ...    ...    ...    ...   ...        ...
168  2026-03-01  125.87   5.40    6.1   2.33  1.21  110.51078
169  2026-04-01  121.06   5.51    5.8   2.37  1.09  110.95732
170  2026-05-01  120.55   5.62    5.6   2.34  1.07  111.03587
171  2026-06-01  124.07    NaN    NaN    NaN  1.12        NaN
172  2026-07-01  121.60    NaN    NaN    NaN  0.95        NaN

[173 rows x 7 columns]

4393	Índice de Confiança do Consumidor 

21084	Inadimplência da carteira de crédito - Pessoas físicas - Total 

24369	Taxa de desocupação - PNADC 

27640 - 27640	Taxa média mensal de juros das operações de crédito não rotativo - Pessoas físicas - Total 

4390 - selic 


24364	Índice de Atividade Econômica do Banco Central (IBC-Br) - com ajuste sazonal

In [4]:
df = df.rename(columns={'4393': 'Confiança_consumidor', 
                        '21084':'Inadimplencia_PF', 
                        '24369':'Desemprego',
                        '27640':'Juros_nao_rotativos_PF',
                        '4390':'SELIC', 
                        '24364':'IBC-Br'})
df

,data,Confiança_consumidor,Inadimplencia_PF,Desemprego,Juros_nao_rotativos_PF,SELIC,IBC-Br
0,2012-03-01,164.42,5.36,8.0,1.95,0.82,98.06309
1,2012-04-01,164.99,5.41,7.8,1.88,0.71,98.38205
2,2012-05-01,163.05,5.51,7.7,1.78,0.74,99.62478
3,2012-06-01,162.35,5.43,7.6,1.70,0.64,100.33945
4,2012-07-01,160.56,5.42,7.5,1.72,0.68,100.51105
...,...,...,...,...,...,...,...
168,2026-03-01,125.87,5.40,6.1,2.33,1.21,110.51078
169,2026-04-01,121.06,5.51,5.8,2.37,1.09,110.95732
170,2026-05-01,120.55,5.62,5.6,2.34,1.07,111.03587
171,2026-06-01,124.07,NaN,NaN,NaN,1.12,NaN
172,2026-07-01,121.60,NaN,NaN,NaN,0.95,NaN